DEMO_JPP/ELBRA2015_V2/Controllers/BerichtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JPP.BL;
using JPP.Domain;
using PagedList;

namespace JPP.UI.Web.MVC.Controllers
{
    [Authorize]
    public class BerichtController : Controller
    {
        
         private AdminManager mgr = new AdminManager();

        // GET: Bericht
         public ActionResult Index(int? page)
        {
            IEnumerable<Bericht> berichten = mgr.GetBerichten();

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(berichten.ToPagedList(pageNumber, pageSize));
        }

        // GET: Bericht/Details/5
        public ActionResult Details(int id)
        {
            Bericht bericht = mgr.GetBericht(id);
            return View(bericht);
        }

        // GET: Bericht/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bericht/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bericht/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Bericht/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bericht/Delete/5
        [Authorize (Roles="Admin")]
        public ActionResult Delete(int id)
        {
            Bericht bericht = mgr.GetBericht(id);

            return View(bericht);
        }

        // POST: Bericht/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                mgr.RemoveBericht(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DEMO_JPP/ELBRA2015_V2/Controllers/RecensieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JPP.BL;
using JPP.Domain;
using PagedList;

namespace JPP.UI.Web.MVC.Controllers
{
    [Authorize]
    public class RecensieController : Controller
    {
        private AdminManager mgr = new AdminManager();
        //TEST
        // GET: Recensie
        public ActionResult Index(int? page)
        {
            IEnumerable<Recensie> recensies = mgr.GetRecensies();


            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(recensies.ToPagedList(pageNumber, pageSize));
           
        }

        // GET: Recensie/Details/5
        public ActionResult Details(int id)
        {

            Recensie recensie = mgr.GetRecensie(id);
            return View(recensie);
        }

        // GET: Recensie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recensie/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recensie/Edit/5
        public ActionResult Edit(int id)
        {
            Recensie recensie = mgr.GetRecensie(id);
            return View(recensie);
        }

        // POST: Recensie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Recensie recensie)
        {
            try
            {
                // TODO: Add update logic here
                mgr.ChangeRecensie(recensie);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recensie/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Recensie recensie = mgr.GetRecensie(id);
            return View(recensie);
        }

        // POST: Recensie/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                mgr.RemoveRecensie(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DEMO_JPP/ELBRA2015_V2/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<a href="@ViewBag.Link">Dit is de activeer link voor debug</a>

DEMO_JPP/ELBRA2015_V2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - JPP Home</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/inlog.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/login.js" type="text/javascript"></script>
    <script src="~/Scripts/websiteAnimation.js" type="text/javascript"></script>

</head>
<body>


    @if(!Request.IsAuthenticated)
    {
        <div id="headerWrapper">
            <div class="navbar navbar-inverse navbar-fixed-top eersteMenu">
                <div class="container">
                    <div class="navbar-header">
                        <a href="@Url.Action("Index", "Home")"><img id="logoImage" src="~/Images/logo.png"></a>

                    </div>

                    @Html.Partial("_LoginPartial", new JPP.UI.Web.MVC.Models.LoginViewModel())
                </div>
            </div>
            <div class="navbar navbar-inverse tweedeMenu">
                <div class="container">
                    <div class="navbar-header">

                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li id="menuItem1"><a>Home</a></li>
                            <li>@Html.ActionLink("Over ons", "Diensten", "Home")</li>
                            <li id="menuItem3"><a>Contact</a></li>
                            <li id="menuItem4"><a>Top 10</a></li>
                            <li>@Html.ActionLink("Registreer", "Register", "Account")</li>

                        </ul>

                    </div>
                </div>
            </div>

        </div>
 
            //bovenste wrapper met JPP afbeelding
            <div id="videoWrapper">
                @*<iframe width="1750" height="800" src="https://www.youtube.com/embed/tdWiDKXegQA" frameborder="0" allowfullscreen ></iframe>*@
                    <div id="mainContent">
                       
                        <a href="#wrapper2" id="centraleButton">Ontdek meer!</a>
                        @*<img id="playButton" src="~/Images/websitePage logos/iconPlay.png" alt="play button" />*@
                    </div>

             
 

            </div>
        



 

        //eerste inhoud
        <div id="mainWrapper">
            <div class="container body-content">
      
                @RenderBody()


            </div>

        </div>

       
        //registreer
        <div id="extraWrapper">
            <div class="container body-content">
                <div class="row">
                    <h1>Top 10</h1>
                   
                    <hr />
                </div>
             </div>

        </div>
        //afbeelding leuven
        <div id="fotoWrapper">
            <div class="container body-content">
                <div class="jumbotron">
                    <h1>Bouw mee aan het Leuven van morgen!</h1>
                    <p class="lead">Met dank aan onze sponsors</p>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 centraal2">

                    <a href="@Url.Action("Index", "Bericht")"><img src="~/Images/sponsors logos/iconLeuven.png"></a>
                    <h2>Leuven</h2>
                </div>
                <div class="col-md-4 centraal2">

                    <a href="@Url.Action("Index", "Recensie")"><img src="~/Images/sponsors logos/iconKULeuven.png"></a>
                    <h2>KU Leuven</h2>
                </div>
                <div class="col-md-4 centraal2">

                    <a href="@Url.Action("Index", "Admin")"><img src="~/Images/sponsors logos/iconTreeCompany2.png"></a>
                    <h2>treecompany</h2>
                </div>

            </div>
              
        </div>
        //laatste wrapper
        <div id="wrapper4">
            <div class="container body-content">
                <div class="row">
                    @Html.Partial("~/Views/Home/About.cshtml")
                    @Html.Partial("~/Views/Home/Contact.cshtml")
                   
                 </div>
             </div>
          
            <div id="to-top">Ga naar de Top</div>
        </div>
        <div id="footerWrapper">
            <footer id="socialFooter">
                <ul class="footerMenu">
                    <li><a href="#"><img src="~/Images/socialMedia icons/twitter.png" alt="TWITTER" /></a></li>
                    <li><a href="#"><img src="~/Images/socialMedia icons/fb.png" alt="FACEBOOK" /></a></li>
                    <li><a href="#"><img src="~/Images/socialMedia icons/google.png" alt="GOOGLE+" /></a></li>

                </ul>
            </footer>

            <footer class="footer">
                <p>&copy; @DateTime.Now.Year - Novartis</p>
                <ul class="footerMenu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
            </footer>
        </div>

    }

  


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

DEMO_JPP/ELBRA2015_V2/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - JPP Home</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/inlog.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/login.js" type="text/javascript"></script>
    <script src="~/Scripts/websiteAnimation.js" type="text/javascript"></script>

</head>
<body>


    @if (Request.IsAuthenticated)
    {

        <div class="navbar navbar-inverse navbar-fixed-top eersteMenu">
            <div class="container">
                <div class="navbar-header">
                    <a href="@Url.Action("Index", "Home")"><img id="logoImage" src="~/Images/logo.png"></a>

                </div>

                @Html.Partial("_LoginPartial", new JPP.UI.Web.MVC.Models.LoginViewModel())
            </div>
        </div>
        <div class="navbar navbar-inverse tweedeMenu">
            <div class="container">
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Mijn account", "Index", "Manage")</li>

                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Admin paneel", "Index", "Admin")</li>

                        }
                        @if (User.IsInRole("Moderator"))
                        {
                            <li id="specialMenuItem">@Html.ActionLink("Moderator paneel", "Index", "Admin")</li>


                        }


                    </ul>

                </div>
            </div>
        </div>

        <div id="mainWrapper2">
            <div class="container body-content">
                @RenderBody()
                <hr />

            </div>

        </div>
                        //afbeelding leuven +footer
                        <div id="fotoWrapper">
                            <div class="container body-content">
                                <div class="jumbotron">
                                    <h1>Bouw mee aan het Leuven van morgen!</h1>
                                    <p class="lead">Met dank aan onze sponsors</p>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 centraal2">

                                    <a href="@Url.Action("Index", "Bericht")"><img src="~/Images/sponsors logos/iconLeuven.png"></a>
                                    <h2>Leuven</h2>
                                </div>
                                <div class="col-md-4 centraal2">

                                    <a href="@Url.Action("Index", "Recensie")"><img src="~/Images/sponsors logos/iconKULeuven.png"></a>
                                    <h2>KU Leuven</h2>
                                </div>
                                <div class="col-md-4 centraal2">

                                    <a href="@Url.Action("Index", "Admin")"><img src="~/Images/sponsors logos/iconTreeCompany2.png"></a>
                                    <h2>treecompany</h2>
                                </div>

                            </div>

                         
                            <div id="to-top">Ga naar de Top</div>
                        </div>
        
        <div>

            <footer id="socialFooter">
                <ul class="footerMenu">
                    <li><a href="#"><img src="~/Images/socialMedia icons/twitter.png" alt="TWITTER" /></a></li>
                    <li><a href="#"><img src="~/Images/socialMedia icons/fb.png" alt="FACEBOOK" /></a></li>
                    <li><a href="#"><img src="~/Images/socialMedia icons/google.png" alt="GOOGLE+" /></a></li>

                </ul>
            </footer>

            <footer class="footer">
                <p>&copy; @DateTime.Now.Year - Novartis</p>
                <ul class="footerMenu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
            </footer>
        </div>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>